name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      greeting:
        description: 'Greeting message'
        required: true
        default: 'Hello, world!'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: echo "${{ github.event.inputs.greeting }}"
      
    - name: Echo Secrets
      env:
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SF_SECURITY_TOKEN: ${{ secrets.SF_SECURITY_TOKEN }}
      run: echo $SF_USERNAME
